### ISSUE TITLE
Add DotNetUtilities.cs back for 'dotnet' framework

### ISSUE THREAD

**Issue by jstedfast** [onovotny/BouncyCastle-PCL#16]
I'm not sure if this belongs here or in bc-csharp proper, but it would be really helpful to have the DotNetUtilities class added back into the nuget for 'dotnet'.

**Comment by jstedfast** [comment]
Hmmm, this may not be entirely possible.

X509Certificate is missing GetRawCertData(), although that could be fixed by using the Export() method with X509ContentType.Cert.

However, the GetKeyPair() methods do not look possible to get working under dnx due to missing classes such as DSA and RSA.

**Comment by onovotny** [comment]
So two things:

1.  Looks like .NET Core is busy implementing the System.Cryptography stuff here: https://github.com/dotnet/corefx/tree/master/src so it may be possible for their RC2 release
2.  Issues should be opened in the main https://github.com/bcgit/bc-csharp repo. All the code here has been merged there.
