### ISSUE TITLE
Index out of Range Exception with Sha.DoFinal method

### ISSUE THREAD

**Issue by glcjr** [onovotny/BouncyCastle-PCL#6]
I am getting an System.IndexOutOfRangeException in crypto.dll and the debuger stops on line 46 of pack.cs. I was trying to use SHA512 but switched it to SHA1 to see if the same exception occurred and it does. I'm just trying to do a simple SHA512 hash of a string in a portable class library.

Here's my code:

public static string MakeHash(string input)
        {
            string temp = "";
            IDigest hasher = new Sha512Digest();
            byte[] data = new byte[hasher.GetDigestSize()]; 
            data = Hex.Decode(input);
            hasher.BlockUpdate(data, 0, data.Length);
            hasher.DoFinal(data, 0);
            temp = Hex.ToHexString(data);
            return temp;
        }

I started commenting things out and running it and the exception is definitely thrown by the DoFinal method as the application actually starts without that line.

**Comment by onovotny** [comment]
Does this happen with the non-portable version of BouncyCastle? I'd recommend a bug report in the bcgit repo.
________________________________

**Comment by glcjr** [comment]
Yep it does. I hadn't tried the non portable one before as I've always used the Net built in cryptography so I didn't even to think to test the other one to see if it was their error. I'll post to theirs.

**Comment by glcjr** [comment]
They decided its not a bug... http://www.bouncycastle.org/jira/browse/BMA-135#add-comment

even though I ended up having to replace Hex.Decode with my own function in order to get it to work...
