### ISSUE TITLE
Please sign the assemblies

### ISSUE THREAD

**Issue by utillity** [onovotny/BouncyCastle-PCL#8]
Hi! can you please sign these assemblies and release a new NuGet package? thanks!

**Comment by onovotny** [comment]
This is dup of #3 and has already been done in https://github.com/onovotny/BouncyCastle-PCL/commit/38d1c791df1a4ec2c4c9cba05101c5727a829634 and released as part of 1.8-rc2

**Comment by utillity** [comment]
thank you! I got your source and indeed the project contains the SNK files and compiles fine. but the NuGet package "Portable.BouncyCastle" Version 1.7.0.2 contains an unsigned version! Please check and update the according NuGet package. thank you!

**Comment by onovotny** [comment]
1.7.0.2 is not signed. You have to use 1.8.0-rc2 for that. Make sure that pre-release packages are enabled when you search nuget/install.

Thanks

**Comment by utillity** [comment]
allright, thanks
